version: '3.7'
services:
  app:
    build: .
    volumes:
      - .:/app/robles
      # When working on videos
      #- ../videos/video-aiar:/data/src
      # When working on books
      #- ../../books/alg:/data/src
      # When working on pablo
      #- ../../sites/pablo:/data/src
      # When working on m3
      - ../../m3/m3-devtest:/data/src
    command: bin/robles module serve
    env_file: .env
    environment:
      - IMAGES_CDN_HOST=assets.robles.kodeco.com
    ports:
      - "4567:4567"
      - "35729:35729"
  snapshot:
    image: browserless/chrome
    ports:
      - "3000:3000"
    # volumes:
    # When working on videos
    #   - ../video-aiar:/data/src
