version: '3.7'
services:
  app:
    build: .
    volumes:
      - .:/app/robles
      - ../../videos/video-aiar:/data/src
      #- ../../books/mad:/data/src
    command: bin/robles video serve
    env_file: .env
    ports:
      - "4567:4567"
      - "35729:35729"
  snapshot:
    image: browserless/chrome
    ports:
      - "3000:3000"
    volumes:
      - ../../videos/video-aiar:/data/src
