version: '3.7'
services:
  app:
    build: .
    volumes:
      - .:/app/robles
      - ../../videos/video-g1:/data/src
    command: bin/robles serve
    env_file: .env
    ports:
      - "4567:4567"
      - "35729:35729"
