# frozen_string_literal: true

CI = ENV['CI']
GITHUB_EVENT_NAME = ENV['EVENT_NAME']
GITHUB_REPOSITORY = ENV['GITHUB_REPOSITORY']
GITHUB_SHA = ENV['GITHUB_SHA']
GITHUB_TOKEN = ENV['GITHUB_TOKEN']
GITHUB_WORKSPACE = ENV['GITHUB_WORKSPACE']
