# frozen_string_literal: true

REPO_ALEXANDRIA_SERVICE_API_TOKEN_PRODUCTION = ENV['REPO_ALEXANDRIA_SERVICE_API_TOKEN_PRODUCTION']
REPO_ALEXANDRIA_SERVICE_API_TOKEN_STAGING = ENV['REPO_ALEXANDRIA_SERVICE_API_TOKEN_STAGING']
REPO_AWS_ACCESS_KEY_ID_PRODUCTION = ENV['REPO_AWS_ACCESS_KEY_ID_PRODUCTION']
REPO_AWS_ACCESS_KEY_ID_STAGING = ENV['REPO_AWS_ACCESS_KEY_ID_STAGING']
REPO_AWS_SECRET_ACCESS_KEY_PRODUCTION = ENV['REPO_AWS_SECRET_ACCESS_KEY_PRODUCTION']
REPO_AWS_SECRET_ACCESS_KEY_STAGING = ENV['REPO_AWS_SECRET_ACCESS_KEY_STAGING']
REPO_SLACK_BOT_TOKEN = ENV['REPO_SLACK_BOT_TOKEN']
REPO_SLACK_WEBHOOK_URL = ENV['REPO_SLACK_WEBHOOK_URL']
