# frozen_string_literal: true

REPO_ALEXANDRIA_SERVICE_API_TOKEN_PRODUCTION = ENV.fetch('REPO_ALEXANDRIA_SERVICE_API_TOKEN_PRODUCTION', nil)
REPO_ALEXANDRIA_SERVICE_API_TOKEN_STAGING = ENV.fetch('REPO_ALEXANDRIA_SERVICE_API_TOKEN_STAGING', nil)
REPO_BETAMAX_SERVICE_API_TOKEN_PRODUCTION = ENV.fetch('REPO_BETAMAX_SERVICE_API_TOKEN_PRODUCTION', nil)
REPO_BETAMAX_SERVICE_API_TOKEN_STAGING = ENV.fetch('REPO_BETAMAX_SERVICE_API_TOKEN_STAGING', nil)
REPO_AWS_ACCESS_KEY_ID_PRODUCTION = ENV.fetch('REPO_AWS_ACCESS_KEY_ID_PRODUCTION', nil)
REPO_AWS_ACCESS_KEY_ID_STAGING = ENV.fetch('REPO_AWS_ACCESS_KEY_ID_STAGING', nil)
REPO_AWS_SECRET_ACCESS_KEY_PRODUCTION = ENV.fetch('REPO_AWS_SECRET_ACCESS_KEY_PRODUCTION', nil)
REPO_AWS_SECRET_ACCESS_KEY_STAGING = ENV.fetch('REPO_AWS_SECRET_ACCESS_KEY_STAGING', nil)
REPO_SLACK_BOT_TOKEN = ENV.fetch('REPO_SLACK_BOT_TOKEN', nil)
REPO_SLACK_WEBHOOK_URL = ENV.fetch('REPO_SLACK_WEBHOOK_URL', nil)
