name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - development

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: robles

jobs:
  Run tests.
  See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi
      
      - name: Notify slack - test results
        uses: voxmedia/github-action-slack-notify-build@v1
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel: circleci
          status: FAILED
          color: danger

  # Push image to DockerHub.
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Notify slack - build starting
        uses: voxmedia/github-action-slack-notify-build@v1
        if: success()
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel: build
          status: STARTING
          color: warning

      - uses: actions/checkout@v2

      - name: Log into GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Log in to DockerHub registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u razewareci --password-stdin

      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Push image to DockerHub
        run: |
          IMAGE_ID=razeware/$IMAGE_NAME
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Prefix tags with 'release'
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=release-$VERSION

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          [ "$VERSION" == "development" ] && VERSION=staging

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push image to GitHub
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Prefix tags with 'release'
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=release-$VERSION

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          [ "$VERSION" == "development" ] && VERSION=staging

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Logout of DockerHub Registry
        if: ${{ always() }}
        run: docker logout

      - name: Logout of GitHub Docker Registry
        if: ${{ always() }}
        run: docker logout docker.pkg.github.com

      - name: Notify slack - build result successful
        uses: voxmedia/github-action-slack-notify-build@v1
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: build
          status: SUCCESS
          color: good

      - name: Notify slack - build result failed
        uses: voxmedia/github-action-slack-notify-build@v1
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: build
          status: FAILED
          color: danger
